### ISSUE TITLE
"Cannot find scene with key=loading" on iOS Simulator

### ISSUE THREAD

**Issue by adrianmcli** [inProgress-team/react-native-meteor-router-flux#2]
This error shows up on both Android and iOS. However, for the Android one, it shows up only in the console, but on iOS it shows up as a big red screen:

![error screenshot](http://i.imgur.com/qznUdDM.png)

I can dismiss it and the app seems to run fine, but this is quite annoying.

**Comment by hyperh** [comment]
Looks like it's this `const navigationState = selected[0] || console.error("Cannot find scene with key="+selectedKey);`

I see it in my Chrome debugger too, but it doesn't pop up the red screen on my Android emulator so maybe it's a iOS simulator thing.

``` js
//Line 19, meteorSwitch.js
const navState = props.navigationState;
const selector = props.selector || console.error("selector should be defined");
const selectedKey = selector(getMeteorData(), props) || console.error("selector should return key");
const selected = navState.children.filter(el=>el.sceneKey==selectedKey) || console.error("key="+selectedKey+" doesn't exist");
const navigationState = selected[0] || console.error("Cannot find scene with key="+selectedKey);

if (!navigationState || navigationState.key != navState.children[navState.index].key){
    Actions[selectedKey]();
}
```

@Mokto What's the point of line 22-23 (`const selected...`, `const navigationState...`)? I tried removing them and also removing the if statement and the app runs fine for me. I'm guessing at a high level, you don't want to fire `Actions[sceneKey]` if you are on that scene already?  My navState children always contained 1 child so selected was always undefined for me.

**Comment by Mokto** [comment]
@adrianmc Can you show me your routes please ?

@hyperh Can you also show me your routes please ? 

If I remove the lines your mentioned, my app stays on loading scene because the action is not triggered.

See https://github.com/aksonov/react-native-router-flux/blob/master/src/Switch.js

**Comment by adrianmcli** [comment]
@Mokto, this is what I have in the render function at the root of my app:

``` jsx
    const scenes = Actions.create(
      <Scene key="root" component={meteorSwitch(getMeteorData)} selector={selector}>
        <Scene key="login" component={Login} title="Login" hideNavBar={true} />
        <Scene key="loading" component={Loading} title="Loading" hideNavBar={true} />
        <Scene key="loggedIn">
          <Scene key="teams" component={Teams} title="Teams" />
          <Scene key="convos" component={Convos} />
          <Scene key="chat" component={Chat} />
        </Scene>
      </Scene>
    );

    return (
      <Router scenes={scenes} />
    );
```

**Comment by hyperh** [comment]
I have something very similar

``` js
    const scenes = Actions.create(
      <Scene key="root" component={meteorSwitch(getMeteorData)} selector={selector}>
        <Scene key="login" component={Login} title="Login" hideNavBar={true} />
        <Scene key="loading" component={Loading} title="Loading" hideNavBar={true} />
        <Scene key="loggedIn">
          <Scene key="list" component={List} title="List" />
        </Scene>
      </Scene>
    );

    return (
      <Router scenes={scenes} />
    );
```

**Comment by Mokto** [comment]
Ok that is weird, my code is exactly the same. What is your RN Router Flux npm version please ?

I might be asking you a reproduction of your bug...

**Comment by hyperh** [comment]
I have the following 

```
    "react-native": "^0.24.1",
    "react-native-meteor": "^1.0.0-beta31",
    "react-native-meteor-router-flux": "^1.0.2",
    "react-native-router-flux": "^3.22.22",
```

**Comment by enbashi** [comment]
I ran into the same problem. According to https://github.com/aksonov/react-native-router-flux/blob/master/docs/OTHER_INFO.md , Switch feature should used together with tabs={true} property. If you don't use a tabBar like in both examples provided by @hyperh and @adrianmc, `navState.children` will return either the selected scene only or an empty array while the selector transitions from a scene to another causing `navigationState` to be undefined in that case resulting in the error. However, if you use `tabs={true}` at the root scene as intended, `navState.children` will always return all the available scenes regardless of which one is returned by the selector. 

Maybe you can change the code to use `navState.scenes` instead of `navState.children` since it always has all the available scenes?

**Comment by Mokto** [comment]
Sorry for the delay.

Thanks for pointing this out, @enbashi !

Yes, tabs={true} is needed on your parent Scene. You can use it even without a tabbar, this is what I do, and it's working ;)

I'll try your solution when I get time available. (navState.scenes into navState.children)

**Comment by hyperh** [comment]
Hmm I tried the following 

```
    const getMeteorData = () => {
      return {
        connected: Meteor.status().connected,
        user: Meteor.user(),
        loggingIn: Meteor.loggingIn(),
      };
    };

    const selector = (data, props) => {
      if (!data.connected || data.loggingIn) { return 'loading'; }
      else if (!data.user) { return 'login'; }
      return 'loggedIn';
    };

      const scenes = Actions.create(
      <Scene key="root" component={meteorSwitch(getMeteorData)} selector={selector} tabs={true} hideTabBar={true}>
        <Scene key="login" component={Login} title="Login" hideNavBar={true} />
        <Scene key="loading" component={Loading} title="Loading" hideNavBar={true} />
        <Scene key="loggedIn">
          ...child scenes
        </Scene>
      </Scene>
      );

   return (
      <Router scenes={scenes} />
    );
```

All I ever get is my scene "loading" showing up. It never goes to the login page. However, when I have `tabs={false}` it properly goes to the login page if you aren't logged in.

**Comment by Mokto** [comment]
Same problem here. I'm right now trying to use createContainer with RNRF Switch Component.

Have you found a workaround ?

**Comment by Mokto** [comment]
Well I did found a workaround, but it is not pretty :

https://github.com/inProgress-team/react-native-meteor/blob/master/README.md#react-native-router-flux

Please let me know if you found something else.

I'm deprecating this repository since it now works with createContainer and official Switch component.
